/**
 * Static world-country data (generated by scripts/build-countries.mjs):
 *  - /countries.geojson      polygons with properties { a2, name }, ids = alpha-2 (upper case)
 *  - /country-bounds.json    { [A2]: [west, south, east, north] } from each country's main landmass
 */
export const COUNTRIES_URL = '/countries.geojson'
const BOUNDS_URL = '/country-bounds.json'

/**
 * Nominatim returns codes for some territories that the dataset folds into a
 * parent polygon (Réunion → France, Svalbard → Norway…). Map them so the
 * parent country lights up rather than nothing.
 */
const ALIAS: Record<string, string> = {
  gf: 'fr', gp: 'fr', mq: 'fr', re: 'fr', yt: 'fr',
  sj: 'no', bv: 'no',
  bq: 'nl',
  um: 'us',
  tk: 'nz',
}

/** Memory country code (lowercase alpha-2) → GeoJSON feature id, or null when unmapped. */
export const toDatasetCode = (countryCode: string): string | null => {
  const code = countryCode.toLowerCase()
  const mapped = ALIAS[code] ?? code
  return /^[a-z]{2}$/.test(mapped) ? mapped.toUpperCase() : null
}

type Bounds = [number, number, number, number]
let boundsPromise: Promise<Record<string, Bounds>> | null = null

const loadBounds = () =>
  (boundsPromise ??= fetch(BOUNDS_URL)
    .then((r): Promise<Record<string, Bounds>> => (r.ok ? r.json() : Promise.resolve({})))
    .catch((): Record<string, Bounds> => ({})))

/** Bounds for fitBounds, or null when the country has no polygon in the dataset. */
export async function countryBoundsFor(countryCode: string): Promise<[[number, number], [number, number]] | null> {
  const id = toDatasetCode(countryCode)
  if (!id) return null
  const b = (await loadBounds())[id]
  if (!b) return null
  return [
    [b[0], b[1]],
    [b[2], b[3]],
  ]
}
